# permissions for end users to view plovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plover-viewer-role
rules:
- apiGroups:
  - canarian.canarian.io
  resources:
  - plovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - canarian.canarian.io
  resources:
  - plovers/status
  verbs:
  - get
